// <auto-generated />
using System;
using KoudakMalzeme.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoudakMalzeme.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260102123435_EtiketAlaniEklendi")]
    partial class EtiketAlaniEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KoudakMalzeme.Shared.Entities.Emanet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlanPersonelId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MalzemeciNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanlananIadeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TeslimAlmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.Property<int?>("VerenPersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlanPersonelId");

                    b.HasIndex("UyeId");

                    b.HasIndex("VerenPersonelId");

                    b.ToTable("Emanetler");
                });

            modelBuilder.Entity("KoudakMalzeme.Shared.Entities.EmanetDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlinanAdet")
                        .HasColumnType("int");

                    b.Property<int>("EmanetId")
                        .HasColumnType("int");

                    b.Property<int>("IadeEdilenAdet")
                        .HasColumnType("int");

                    b.Property<int>("IadeTalepEdilenAdet")
                        .HasColumnType("int");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmanetId");

                    b.HasIndex("MalzemeId");

                    b.ToTable("EmanetDetaylari");
                });

            modelBuilder.Entity("KoudakMalzeme.Shared.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IlkGirisYapildiMi")
                        .HasColumnType("bit");

                    b.Property<string>("OkulNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfilResmiYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("KoudakMalzeme.Shared.Entities.Malzeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etiketler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GorselYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuncelStok")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamStok")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Malzemeler");
                });

            modelBuilder.Entity("KoudakMalzeme.Shared.Entities.Emanet", b =>
                {
                    b.HasOne("KoudakMalzeme.Shared.Entities.Kullanici", "AlanPersonel")
                        .WithMany()
                        .HasForeignKey("AlanPersonelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KoudakMalzeme.Shared.Entities.Kullanici", "Uye")
                        .WithMany("AldigiEmanetler")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoudakMalzeme.Shared.Entities.Kullanici", "VerenPersonel")
                        .WithMany()
                        .HasForeignKey("VerenPersonelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AlanPersonel");

                    b.Navigation("Uye");

                    b.Navigation("VerenPersonel");
                });

            modelBuilder.Entity("KoudakMalzeme.Shared.Entities.EmanetDetay", b =>
                {
                    b.HasOne("KoudakMalzeme.Shared.Entities.Emanet", "Emanet")
                        .WithMany("EmanetDetaylari")
                        .HasForeignKey("EmanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoudakMalzeme.Shared.Entities.Malzeme", "Malzeme")
                        .WithMany("EmanetGecmisi")
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emanet");

                    b.Navigation("Malzeme");
                });

            modelBuilder.Entity("KoudakMalzeme.Shared.Entities.Emanet", b =>
                {
                    b.Navigation("EmanetDetaylari");
                });

            modelBuilder.Entity("KoudakMalzeme.Shared.Entities.Kullanici", b =>
                {
                    b.Navigation("AldigiEmanetler");
                });

            modelBuilder.Entity("KoudakMalzeme.Shared.Entities.Malzeme", b =>
                {
                    b.Navigation("EmanetGecmisi");
                });
#pragma warning restore 612, 618
        }
    }
}
